package report

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/chebilax/sphinxor/internal/export/cerbos"
)

// WriteExport renders result to w in the given format — the companion
// report ADR 0009 §4 requires alongside the generated policy files
// themselves, so a reader can see everything an export doesn't cover
// without opening every policy file to find the inline comments.
func WriteExport(w io.Writer, result cerbos.Result, format Format) error {
	switch format {
	case FormatJSON:
		return writeExportJSON(w, result)
	case FormatMarkdown, "":
		return writeExportMarkdown(w, result)
	default:
		return fmt.Errorf("report: unknown format %q", format)
	}
}

func writeExportJSON(w io.Writer, result cerbos.Result) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

func writeExportMarkdown(w io.Writer, result cerbos.Result) error {
	var b strings.Builder

	b.WriteString("# Cerbos Export Report\n\n")
	b.WriteString("Generated by `sphinxor export cerbos`. Review before deploying — this is not a\n")
	b.WriteString("deploy-ready artifact. See docs/decisions/0009-cerbos-exporter.md for the safety\n")
	b.WriteString("posture behind what is and isn't included below.\n\n")
	fmt.Fprintf(&b, "%d rule(s) exported, %d omission(s), %d unverified role reference(s).\n\n",
		len(result.Rules), len(result.Omissions), len(result.UnverifiedRoles))

	b.WriteString("## Omissions\n\n")
	if len(result.Omissions) == 0 {
		b.WriteString("None.\n\n")
	} else {
		b.WriteString("Endpoints below were **not** granted to anyone in the exported policy — Cerbos\n")
		b.WriteString("denies by default for any action with no matching rule, so omission is the safe\n")
		b.WriteString("state, not a guess.\n\n")
		b.WriteString("| Method | Path | Reason | Detail |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, o := range result.Omissions {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
				o.Endpoint.HTTPMethod, o.Endpoint.Path, o.Reason, escapeTableCell(o.Detail))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Unverified Roles\n\n")
	if len(result.UnverifiedRoles) == 0 {
		b.WriteString("None.\n\n")
	} else {
		b.WriteString("These roles **were** exported — Sphinxor just couldn't confirm the role name\n")
		b.WriteString("against a known declaration (e.g. a bare string literal with no backing enum).\n")
		b.WriteString("Verify the name is correct before deploying.\n\n")
		b.WriteString("| Resource | Action | Role | Endpoint |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, u := range result.UnverifiedRoles {
			fmt.Fprintf(&b, "| %s | %s | %s | %s %s |\n",
				u.Resource, u.Action, u.Role, u.Endpoint.HTTPMethod, u.Endpoint.Path)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Exported Rules\n\n")
	if len(result.Rules) == 0 {
		b.WriteString("None.\n")
	} else {
		anyWildcard := false
		b.WriteString("| Resource | Action | Roles | Endpoints |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, r := range result.Rules {
			var endpoints []string
			for _, e := range r.Endpoints {
				endpoints = append(endpoints, string(e.HTTPMethod)+" "+e.Path)
			}
			for _, role := range r.Roles {
				if role == "*" {
					anyWildcard = true
				}
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
				r.Resource, r.Action, strings.Join(r.Roles, ", "), strings.Join(endpoints, "; "))
		}
		if anyWildcard {
			b.WriteString("\n`*` is Cerbos's own special role value: any authenticated principal, regardless\n")
			b.WriteString("of role. Sphinxor only ever generates it when the source code checks for\n")
			b.WriteString("authentication but no specific role — never as a fallback or a guess.\n")
		}
	}

	_, err := io.WriteString(w, b.String())
	return err
}

func escapeTableCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
