package cerbos

import (
	"fmt"
	"sort"
	"strings"
)

// header is the mandatory review-before-deploying marker (ADR 0009 §3),
// written into every generated policy file itself — not only into
// surrounding docs or a README that might not travel with the file when
// it's copied into a deploy pipeline.
const header = "# Generated by sphinxor -- review before deploying. Not deploy-ready.\n" +
	"# See export-report.md for everything this export could not translate.\n"

// ResourceNames returns every resource r has anything to say about — a
// Rule or an Omission — sorted. A resource with only Omissions (every
// endpoint on that controller was omitted) still gets a name here: its
// policy file is worth generating with zero rules, so the omissions are
// visible as inline comments right where a human would look for them, not
// only in the companion report.
func ResourceNames(r Result) []string {
	seen := make(map[string]bool)
	for _, rule := range r.Rules {
		seen[rule.Resource] = true
	}
	for _, o := range r.Omissions {
		if o.Resource != "" {
			seen[o.Resource] = true
		}
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// entry is either a real Rule or an omission comment, ordered together by
// action so the rendered file reads as one coherent list of "what happens
// per action" rather than rules and gaps in separate, disconnected places.
type entry struct {
	action  string
	sortKey string // action, then path for omissions, for a stable order
	rule    *Rule
	omitted *Omission
}

// RenderPolicy renders one Cerbos resource policy YAML document for
// resource, using only the parts of r that belong to it.
func RenderPolicy(resource string, r Result) string {
	unverifiedByRule := make(map[[2]string]map[string]bool) // [action, role] -> flagged
	for _, u := range r.UnverifiedRoles {
		if u.Resource != resource {
			continue
		}
		key := [2]string{u.Action, u.Role}
		if unverifiedByRule[key] == nil {
			unverifiedByRule[key] = make(map[string]bool)
		}
		unverifiedByRule[key][u.Role] = true
	}
	unverified := func(action, role string) bool {
		return unverifiedByRule[[2]string{action, role}][role]
	}

	var entries []entry
	for i := range r.Rules {
		rule := r.Rules[i]
		if rule.Resource != resource {
			continue
		}
		entries = append(entries, entry{action: rule.Action, sortKey: rule.Action, rule: &rule})
	}
	for i := range r.Omissions {
		o := r.Omissions[i]
		if o.Resource != resource {
			continue
		}
		entries = append(entries, entry{
			action:  strings.ToLower(string(o.Endpoint.HTTPMethod)),
			sortKey: strings.ToLower(string(o.Endpoint.HTTPMethod)) + " " + o.Endpoint.Path,
			omitted: &o,
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].sortKey < entries[j].sortKey })

	hasRule := false
	for _, e := range entries {
		if e.rule != nil {
			hasRule = true
			break
		}
	}

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("apiVersion: \"api.cerbos.dev/v1\"\n")
	b.WriteString("resourcePolicy:\n")
	b.WriteString("  version: \"default\"\n")
	fmt.Fprintf(&b, "  resource: %q\n", resource)

	if !hasRule {
		// A `rules:` key followed only by comment lines parses as YAML
		// null, not an empty sequence — confirmed against a real
		// `cerbos compile` failure, not assumed. An explicit `rules: []`
		// is required whenever there's no real rule item to anchor the
		// block sequence; the omission comments become standalone
		// document comments after it instead.
		b.WriteString("  rules: []\n")
		for _, e := range entries {
			o := e.omitted
			fmt.Fprintf(&b, "  # %s %s -- omitted (%s): %s\n",
				o.Endpoint.HTTPMethod, o.Endpoint.Path, o.Reason, o.Detail)
		}
		return b.String()
	}

	b.WriteString("  rules:\n")
	for _, e := range entries {
		if e.omitted != nil {
			fmt.Fprintf(&b, "    # %s %s -- omitted (%s): %s\n",
				e.omitted.Endpoint.HTTPMethod, e.omitted.Endpoint.Path, e.omitted.Reason, e.omitted.Detail)
			continue
		}
		rule := e.rule
		fmt.Fprintf(&b, "    - actions: [%q]\n", rule.Action)
		b.WriteString("      roles:\n")
		for _, role := range rule.Roles {
			if unverified(rule.Action, role) {
				fmt.Fprintf(&b, "        - %q # role reference could not be verified against a known declaration\n", role)
			} else {
				fmt.Fprintf(&b, "        - %q\n", role)
			}
		}
		b.WriteString("      effect: EFFECT_ALLOW\n")
	}

	return b.String()
}
