package cerbos

import (
	"strings"
	"testing"

	"github.com/chebilax/sphinxor/internal/model"
)

func hasLine(text, substr string) bool {
	for _, line := range strings.Split(text, "\n") {
		if strings.Contains(line, substr) {
			return true
		}
	}
	return false
}

func TestRenderPolicy_HeaderAlwaysPresent(t *testing.T) {
	m := &model.Model{
		Controllers: []model.Controller{{ID: "c1", Name: "UsersController"}},
		Endpoints:   []model.Endpoint{{ID: "e1", HTTPMethod: model.MethodGet, Path: "/users", ControllerID: "c1"}},
		GuardApplications: []model.GuardApplication{
			{ID: "g1", EndpointID: "e1", GuardName: "Roles"},
		},
		RoleReferences: []model.RoleReference{
			{ID: "ref1", GuardApplicationID: "g1", RawLiteral: "admin"},
		},
	}
	out := RenderPolicy("users", Translate(m))

	if !strings.HasPrefix(out, "# Generated by sphinxor -- review before deploying. Not deploy-ready.") {
		t.Fatalf("policy does not start with the mandatory review header:\n%s", out)
	}
	if !hasLine(out, "resource: \"users\"") {
		t.Errorf("expected resource: %q in output:\n%s", "users", out)
	}
	if !hasLine(out, `actions: ["get"]`) {
		t.Errorf("expected a get action rule, got:\n%s", out)
	}
}

func TestRenderPolicy_ZeroRulesEmitsExplicitEmptyArray(t *testing.T) {
	m := &model.Model{
		Controllers: []model.Controller{{ID: "c1", Name: "HealthController"}},
		Endpoints:   []model.Endpoint{{ID: "e1", HTTPMethod: model.MethodGet, Path: "/health", ControllerID: "c1"}},
	}
	out := RenderPolicy("health", Translate(m))

	// A `rules:` key followed only by comments parses as YAML null, not an
	// empty sequence (confirmed against a real cerbos compile failure) —
	// the explicit `rules: []` is required, not cosmetic.
	if !hasLine(out, "rules: []") {
		t.Fatalf("expected an explicit \"rules: []\" when there are no confirmed rules, got:\n%s", out)
	}
	if !hasLine(out, "GET /health") {
		t.Errorf("expected the omission comment to mention the omitted endpoint, got:\n%s", out)
	}
}

func TestRenderPolicy_UnverifiedRoleCommentedInline(t *testing.T) {
	m := &model.Model{
		Controllers: []model.Controller{{ID: "c1", Name: "ThingsController"}},
		Endpoints:   []model.Endpoint{{ID: "e1", HTTPMethod: model.MethodDelete, Path: "/things/:id", ControllerID: "c1"}},
		GuardApplications: []model.GuardApplication{
			{ID: "g1", EndpointID: "e1", GuardName: "Roles"},
		},
		RoleReferences: []model.RoleReference{
			{ID: "ref1", GuardApplicationID: "g1", RoleDeclarationID: nil, RawLiteral: "admin"},
		},
	}
	out := RenderPolicy("things", Translate(m))

	if !hasLine(out, `"admin" # role reference could not be verified against a known declaration`) {
		t.Errorf("expected the unverified role to carry an inline comment, got:\n%s", out)
	}
}

func TestResourceNames_IncludesOmissionOnlyResources(t *testing.T) {
	m := &model.Model{
		Controllers: []model.Controller{{ID: "c1", Name: "HealthController"}},
		Endpoints:   []model.Endpoint{{ID: "e1", HTTPMethod: model.MethodGet, Path: "/health", ControllerID: "c1"}},
	}
	names := ResourceNames(Translate(m))

	if len(names) != 1 || names[0] != "health" {
		t.Fatalf("expected [\"health\"] even though it has zero rules, got %v", names)
	}
}
